name: "dap"
version: "1.0.0"
config-version: 2

profile: "dap"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  dap:
    +materialized: table
    bronze:
      +schema: bronze
      +materialized: view
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table
    semantic:
      time_spine:
        +schema: gold
        +materialized: table

vars:
  # Multi-tenant isolation variable
  # Set via: dbt run --vars '{"tenant_id": "TENANT_001"}'
  tenant_id: null