version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: sample_sales
        description: "Raw IQVIA-like sales fact at pack x geo x month x channel"
        columns:
          - name: period_yyyymm
            tests: [not_null]
          - name: pack_id
            tests: [not_null]
          - name: geo_id
            tests: [not_null]
          - name: channel_id
            tests: [not_null]
      - name: service_events_raw
        description: "Raw service events landing table (PGR and other services)"
        columns:
          - name: event_date
            tests:
              - not_null
          - name: event_time
            tests:
              - not_null
          - name: tenant_id
            tests:
              - not_null
          - name: service
            tests:
              - not_null
          - name: entity_type
            tests:
              - not_null
          - name: entity_id
            tests:
              - not_null
          - name: event_type
            tests:
              - not_null
